Project:
 subscriberid: "1234|5678|9012"
 1234.Key: "ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP|ABCD|EFGH|IJKL|MNOP"
 5678.Key: "QRST|UVWX"
 9012.Key: "YZ"
    